### ISSUE TITLE
Allocation of 250GB volume fails due to rounding error

### ISSUE THREAD

**Issue by jasoncwik** [thecodeteam/csi-scaleio#10]
I requested a PVC of 250GB (250000000000 bytes) and the PVC fails to provision because the SIO CSI is requesting less than 250GB (it's allocating 249108103168 ... 232GiB).

```
I0110 20:09:07.205827       1 controller.go:88] GRPC call: /csi.v0.Controller/CreateVolume
I0110 20:09:07.205835       1 controller.go:89] GRPC request: name:"vxvol-cd41cb7315" capacity_range:<required_bytes:250000000000 > volume_capabilities:<mount:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"storagepool" value:"default" > 
I0110 20:09:07.331820       1 controller.go:91] GRPC response: volume:<capacity_bytes:249108103168 id:"695d57e600000002" > 
I0110 20:09:07.331871       1 controller.go:92] GRPC error: <nil>
```

By inspection, I can see the error around here: https://github.com/thecodeteam/csi-scaleio/blob/master/service/controller.go#L180

250GB ends up being 232.83GiB but since it's integer math, the integer part is lost and sizeInGB ends up being 232 and that's an even multiple of 8 so it allocates a volume of 232GiB. This unfortunately is less than what was requested by the PVC so the allocation fails.

I would expect this bug to exist for any allocation 1 to 1Gi more than a multiple of 8GiB.

Workaround is to ensure you request your PVCs in `Gi` not `G`.

**Comment by codenrhoden** [comment]
This repo is no longer maintained, Closing out old issues before archival.

New repo is at https://github.com/dell/csi-vxflexos
